### ISSUE TITLE
Mounting Deletes Hauling Items

### ISSUE THREAD

**Issue by fizykz** [rheirman/GiddyUpRideAndRoll#22]
Figured I'd at least start the issue.

I have yet to isolate what items specifically nor if this occurs outside of other mods, but certain items when being hauled are destroyed/deleted.

I've noticed serveral times through my last playthroughs/testing sessions that *occasionally* an item goes missing (even if I use a searching mod).  This time I figured out what causes it.  I had one of my animals carrying it and my pawn tried mounting it and poof, gone.

The only item I've confirmed to be the case is the Heavy Charge Blaster.  It's vanilla, but I'm pretty sure it was changed so it could be acquired.

EDIT:
Also occurs with the charge lance.

Example:
![qWlCjUmEFM](https://user-images.githubusercontent.com/19498699/84406052-9df65280-abce-11ea-8e0b-66514a7a4518.gif)

**Comment by rheirman** [comment]
Please provide your hugslib log so I have an idea of what mods you're running with. Press ctrl+f12 after getting the issue. 

I'd also appreciate a test without any other mods. I'm assuming it's a conflict with another mod, since I never experienced this issue, and it's never been reported before. It could also be the result of one of the latest Rimworld updates, but that's less likely.

**Comment by fizykz** [comment]
Haha unfortunately I made a mistake and opened the issue far too quickly before further testing.  If I have a colonist pick it up, then drop it, it also disappears.  If that's the case I'm just assuming it's just not implemented.  My mistake!
